#_*_ coding:utf-8- _*_
print("-"*5+"原始代码打印"+"-"*5)
print('Hello World!')
print('Hello Again')
print('I like typing this.')
print('This is fun.')
print('Yay!Printing')
print("I'd much rather you 'not'.")
print('I "said" do not touch this.')
print("-"*5+"study drills打印"+"-"*5)
print('Hello World!',end="")
print('Hello Again',end="")
print('I like typing this.',end="")
print('This is fun.',end="")
print('Yay!Printing',end="")
print("I'd much rather you 'not'.\n")
print('I "said" do not touch this.')